version: '3.8'

services:
  mysql-container:
    image: mysql:8.2.0
    container_name: mysql-aluraflix
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aluraflix
      MYSQL_USER: user-aluraflix
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: